// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.27.1
// source: chatvault.proto

package chatvaultrpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ChatVaultService_CreateConversation_FullMethodName  = "/chatvaultrpc.ChatVaultService/CreateConversation"
	ChatVaultService_GetConversationList_FullMethodName = "/chatvaultrpc.ChatVaultService/GetConversationList"
	ChatVaultService_SaveChatMessage_FullMethodName     = "/chatvaultrpc.ChatVaultService/SaveChatMessage"
	ChatVaultService_GetChatMessageList_FullMethodName  = "/chatvaultrpc.ChatVaultService/GetChatMessageList"
)

// ChatVaultServiceClient is the client API for ChatVaultService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ChatVaultServiceClient interface {
	CreateConversation(ctx context.Context, in *ConversationRequest, opts ...grpc.CallOption) (*ConversationResponse, error)
	GetConversationList(ctx context.Context, in *ConversationListRequest, opts ...grpc.CallOption) (*ConversationListResponse, error)
	SaveChatMessage(ctx context.Context, in *ChatMessageRequest, opts ...grpc.CallOption) (*SaveChatMessageResponse, error)
	GetChatMessageList(ctx context.Context, in *ChatMessageListRequest, opts ...grpc.CallOption) (*ChatMessageListResponse, error)
}

type chatVaultServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewChatVaultServiceClient(cc grpc.ClientConnInterface) ChatVaultServiceClient {
	return &chatVaultServiceClient{cc}
}

func (c *chatVaultServiceClient) CreateConversation(ctx context.Context, in *ConversationRequest, opts ...grpc.CallOption) (*ConversationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConversationResponse)
	err := c.cc.Invoke(ctx, ChatVaultService_CreateConversation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatVaultServiceClient) GetConversationList(ctx context.Context, in *ConversationListRequest, opts ...grpc.CallOption) (*ConversationListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConversationListResponse)
	err := c.cc.Invoke(ctx, ChatVaultService_GetConversationList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatVaultServiceClient) SaveChatMessage(ctx context.Context, in *ChatMessageRequest, opts ...grpc.CallOption) (*SaveChatMessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveChatMessageResponse)
	err := c.cc.Invoke(ctx, ChatVaultService_SaveChatMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatVaultServiceClient) GetChatMessageList(ctx context.Context, in *ChatMessageListRequest, opts ...grpc.CallOption) (*ChatMessageListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChatMessageListResponse)
	err := c.cc.Invoke(ctx, ChatVaultService_GetChatMessageList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChatVaultServiceServer is the server API for ChatVaultService service.
// All implementations must embed UnimplementedChatVaultServiceServer
// for forward compatibility.
type ChatVaultServiceServer interface {
	CreateConversation(context.Context, *ConversationRequest) (*ConversationResponse, error)
	GetConversationList(context.Context, *ConversationListRequest) (*ConversationListResponse, error)
	SaveChatMessage(context.Context, *ChatMessageRequest) (*SaveChatMessageResponse, error)
	GetChatMessageList(context.Context, *ChatMessageListRequest) (*ChatMessageListResponse, error)
	mustEmbedUnimplementedChatVaultServiceServer()
}

// UnimplementedChatVaultServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedChatVaultServiceServer struct{}

func (UnimplementedChatVaultServiceServer) CreateConversation(context.Context, *ConversationRequest) (*ConversationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateConversation not implemented")
}
func (UnimplementedChatVaultServiceServer) GetConversationList(context.Context, *ConversationListRequest) (*ConversationListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetConversationList not implemented")
}
func (UnimplementedChatVaultServiceServer) SaveChatMessage(context.Context, *ChatMessageRequest) (*SaveChatMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveChatMessage not implemented")
}
func (UnimplementedChatVaultServiceServer) GetChatMessageList(context.Context, *ChatMessageListRequest) (*ChatMessageListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetChatMessageList not implemented")
}
func (UnimplementedChatVaultServiceServer) mustEmbedUnimplementedChatVaultServiceServer() {}
func (UnimplementedChatVaultServiceServer) testEmbeddedByValue()                          {}

// UnsafeChatVaultServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChatVaultServiceServer will
// result in compilation errors.
type UnsafeChatVaultServiceServer interface {
	mustEmbedUnimplementedChatVaultServiceServer()
}

func RegisterChatVaultServiceServer(s grpc.ServiceRegistrar, srv ChatVaultServiceServer) {
	// If the following call pancis, it indicates UnimplementedChatVaultServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ChatVaultService_ServiceDesc, srv)
}

func _ChatVaultService_CreateConversation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConversationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatVaultServiceServer).CreateConversation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatVaultService_CreateConversation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatVaultServiceServer).CreateConversation(ctx, req.(*ConversationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatVaultService_GetConversationList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConversationListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatVaultServiceServer).GetConversationList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatVaultService_GetConversationList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatVaultServiceServer).GetConversationList(ctx, req.(*ConversationListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatVaultService_SaveChatMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChatMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatVaultServiceServer).SaveChatMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatVaultService_SaveChatMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatVaultServiceServer).SaveChatMessage(ctx, req.(*ChatMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatVaultService_GetChatMessageList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChatMessageListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatVaultServiceServer).GetChatMessageList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatVaultService_GetChatMessageList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatVaultServiceServer).GetChatMessageList(ctx, req.(*ChatMessageListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ChatVaultService_ServiceDesc is the grpc.ServiceDesc for ChatVaultService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChatVaultService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "chatvaultrpc.ChatVaultService",
	HandlerType: (*ChatVaultServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateConversation",
			Handler:    _ChatVaultService_CreateConversation_Handler,
		},
		{
			MethodName: "GetConversationList",
			Handler:    _ChatVaultService_GetConversationList_Handler,
		},
		{
			MethodName: "SaveChatMessage",
			Handler:    _ChatVaultService_SaveChatMessage_Handler,
		},
		{
			MethodName: "GetChatMessageList",
			Handler:    _ChatVaultService_GetChatMessageList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "chatvault.proto",
}
